-- MySQL Script generated by MySQL Workbench
-- Tue Sep 18 21:01:11 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema blogdb
-- -----------------------------------------------------
-- Schema used with the Film application


-- -----------------------------------------------------
-- Schema blogdb
--
-- Schema used with the Film application
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blogdb` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `blogdb` ;

-- -----------------------------------------------------
-- Table `blogdb`.`User`
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `blogdb`.`Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blogdb`.`Category` ;

CREATE TABLE IF NOT EXISTS `blogdb`.`Category` (
  `CategoryId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Category` VARCHAR(45) NOT NULL,
  `Label` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CategoryId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blogdb`.`Blog`
-- -----------------------------------------------------


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
